export const Constants ={
    SET_LOGIN_DATA: 'SET_LOGIN_DATA',
    SET_LOGOUT: 'SET_LOGOUt',
    SET_URL: 'SET_URL',
    ADD_BOOK_TO_CART: 'ADD_BOOK_TO_CART',
    ADD_BOOK_DETAILS: 'ADD_BOOK_DETAILS',
    EMPTY_BOOK_FROM_CART: 'EMPTY_BOOK_FROM_CART',
    ADD_COUNT: 'ADD_COUNT'
 }